syntax on           " syntax highlighting
set nocompatible              " be iMproved, required
filetype off                  " required

set rtp+=/Users/mm/.dotfiles/.vim/bundle/Vundle.vim
let path="/Users/mm/.dotfiles/.vim/bundle"
let mapleader = " "     " set leader key

" tabs and spaces
set tabstop=2
set shiftwidth=2
set shiftround
set expandtab

let g:airline_powerline_fonts = 1
let g:airline_theme='wombat'
let g:Powerline_symbols = 'fancy'

let g:session_autosave_periodic = 5
let g:session_autosave_silent =true

"Write the old file out when switching between files.
set autowrite

"Display current cursor position in lower right corner.
set ruler

"Show lines numbers
set relativenumber
set number

"Indent stuff
set smartindent
set autoindent

"Highlight searching
set hlsearch

" case insensitive search
set ignorecase
set smartcase

" toggle to paste without indenting
set pastetoggle=<F2>

let g:airline#extensions#tabline#enabled = 1
set timeoutlen=250

if has("autocmd")
 augroup myvimrchooks
  au!
  autocmd bufwritepost .vimrc source ~/.vimrc
 augroup END
endif

call vundle#begin(path)
" Vim + tmux
Plugin 'christoomey/vim-tmux-navigator'
" window swap  leader-yw leader-pw leader-ww
Plugin 'wesQ3/vim-windowswap'

" move easily around the buffer  keys: /, leader-h,l
Plugin 'Lokaltog/vim-easymotion'

"fuzzy file finder  ctrl-p | ctrl-k,j | ctrl-z (select or deselect) | ctrl-x,v,o
Plugin 'kien/ctrlp.vim'

"git wrapper"
Plugin 'tpope/vim-fugitive'
"git gutter"
Plugin 'airblade/vim-gitgutter'
"gitk"
Plugin 'gregsexton/gitv'
"history graph" leader-ut
Plugin 'mbbill/undotree'

" Nerd tree  leader-nt
Plugin 'scrooloose/nerdtree'

"surround text with any text easily  cs[old surr][new surround]
Plugin 'tpope/vim-surround'

"Multiple cursors     ctrl-n,p,x
Plugin 'terryma/vim-multiple-cursors'

" searcher  /f (find current word) leader-/ (find in files)
Plugin 'rking/ag.vim'

" Tagbar  leader-tb
Plugin 'majutsushi/tagbar'

" Commenting  gc,gcc
Plugin 'tpope/vim-commentary'

"open browser"
Plugin 'tyru/open-browser.vim'

"greplace across multiple files interactively
Plugin 'greplace.vim'

" Snippit
Plugin 'garbas/vim-snipmate'

"emmet"
Plugin 'mattn/emmet-vim'

"indent level guide"
Plugin 'nathanaelkane/vim-indent-guides'
Plugin 'editorconfig/editorconfig-vim'

" add end word in rails function and other languages"
Plugin 'tpope/vim-endwise'

" auto close quote, brackets, ..
Plugin 'Raimondi/delimitMate'

" useful for indenting css files"
Plugin 'godlygeek/tabular'

"highlight matching html tab"
Plugin 'gregsexton/MatchTag'

" all vim color schemes"
Plugin 'flazz/vim-colorschemes'
Plugin 'xolox/vim-misc'
" color scheme switcher F8, Shift+F8"
Plugin 'xolox/vim-colorscheme-switcher'

" Lines
Plugin 'bling/vim-airline'
Plugin 'bling/vim-bufferline'

" sessions
Plugin 'xolox/vim-session'

" Completion & Linting
Plugin 'Valloric/YouCompleteMe'
Plugin 'scrooloose/syntastic'

"""" Languages support """"
Plugin 'kchmck/vim-coffee-script'
Plugin 'vim-ruby/vim-ruby'
Plugin 'tpope/vim-markdown'
Plugin 'tpope/vim-haml' "and sass
Plugin 'othree/html5.vim'
Plugin 'digitaltoad/vim-jade'
Plugin 'klen/python-mode'
Plugin 'jelera/vim-javascript-syntax'
Plugin 'elzr/vim-json'
Plugin 'fatih/vim-go'
Plugin 'mxw/vim-jsx'
Plugin 'burnettk/vim-angular'
Plugin 'heavenshell/vim-jsdoc'
Plugin 'rhysd/vim-clang-format'
Plugin 'tpope/vim-rails'

Plugin 'michalliu/sourcebeautify.vim'
call vundle#end()
filetype plugin indent on    " required
source /Users/mm/.dotfiles/.vim-settings
