source /Users/mahmoud/.dotfiles/.globals
source /Users/mahmoud/.dotfiles/.globals
source /Users/mahmoud/.dotfiles/.globals
source /Users/mahmoud/.dotfiles/.globals
source /Users/mahmoud/.dotfiles/.globals
source /Users/mahmoud/.dotfiles/.globals
source /Users/mahmoud/.dotfiles/.globals
source /Users/mahmoud/.dotfiles/.globals
source /Users/mahmoud/.dotfiles/.globals
source /Users/mahmoud/.dotfiles/.globals
source /Users/mahmoud/.dotfiles/.globals
source /Users/mahmoud/.dotfiles/.globals
source /Users/mahmoud/.dotfiles/.globals
source /Users/mahmoud/.dotfiles/.globals
source /Users/mahmoud/.dotfiles/.globals
source /Users/mahmoud/.dotfiles/.globals
source /Users/mahmoud/.dotfiles/.globals
source /Users/mahmoud/.dotfiles/.globals
source /Users/mahmoud/.dotfiles/.globals
source /Users/mahmoud/.dotfiles/.globals
source /Users/mahmoud/.dotfiles/.globals
source /Users/mahmoud/.dotfiles/.globals
source /Users/mahmoud/.dotfiles/.globals
# eval "$(pyenv init -)"
